### ISSUE TITLE
Need an option to render without escaping.

### ISSUE THREAD

**Issue by jamalneufeld** [HubSpot/draft-convert#127]
I'm building a tool with draft-js for building html emails with draft-convert rendering the static output. This tool has been fantastic, however we're running into an issue with escaped characters in the email subject. Things like escaped apostrophes and other characters are not rendered by email clients, so the character code shows up instead. Meanwhile we need other functionality (like mentions) that are text-only to be present in the subject, so we can't bypass using draft-convert.

I've seen the workaround of returning a string in the block renderer, but unfortunately this blocks us from using other Draft functionality in that block.

Question: Before I make it, would you consider a PR which would add the option to _not_ escape block/entity rendering?

**Comment by benbriggs** [comment]
I'm not sure this is something that makes sense within draft-convert's current charter. Right now it's specifically aimed at converting to HTML, and escaping is a big part of that. Because a side effect of not escaping HTML is potential security vulnerabilities I'd also hesitate to have it be a more easily accessible option that a user of `draft-convert` could shoot themselves in the foot with without really knowing what's going on. In the past for email subjects I've had success just passing the result of `convertToHTML` to `unescape` from underscore/lodash/whatever you prefer - would doing that solve your problem?

I have thought about what the best way would be to expand `draft-convert` to handle multiple output types (e.g. markdown) but don't see that happening any time soon. I think making the HTML escaping optional would be great within the context of supporting another output type more officially, but for now I think it should be something that happens outside `draft-convert`.
