### ISSUE TITLE
HTML Node to multiple Content blocks

### ISSUE THREAD

**Issue by tammomueller** [HubSpot/draft-convert#27]
I would like to solve the following issue:

Using convertFromHTML I can convert an image tag to an atomic content block, however I am trying to introduce an unstyled block before and after the image.

htmlToBlock only allows for returning a  1 - to - 1 translation. Is there any way to achieve this 1 - to - many translation, i.e. one HTML node translates into multiple content blocks.

Thanks

**Comment by benbriggs** [comment]
Hi @tammomueller, there currently isn't - the objective of this project is to provide a way for a more direct map between contentState and HTML. After converting to ContentState with `draft-convert` you could run the result through a function that searches for image blocks and returns a modified version that includes the unstyled blocks you're looking for. Since the content state is just an immutable data structure that operation should be relatively straightforward.

**Comment by benbriggs** [comment]
i'm going to close this as i think this functionality is for now outside the scope of draft-convert - like i recommended previous i think a subsequent post-processing function to add the additional block would be effective
