### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by 0rvar** [HubSpot/draft-convert#37]
Generally, it seems issues and pull requests are not given much attention in this repository. I am not whining, but as a user of this repository, it puts me (and the products I work on) in an awkward spot: should we wait, or create a temporary fork? Or a permanent?

I'd love to keep contributing to this library.
If you do not have a lot of time to maintain the project, would you be willing to take on more maintainers?

**Comment by benbriggs** [comment]
The most important issues I've tried to stay pretty on top of. For something like #36 I wanted to make sure anyone reporting issues got a chance to give it a look before merging. Other PRs I haven't gotten a chance to look at yet but they didn't directly affect the functionality of the project.

Since the purpose of this library is to be a direct map between ContentState and HTML, activity should decrease as that mapping gets closer and closer to the ideal. I'll try to do a better job to implement or review solutions to issues as they come in. I definitely welcome PRs but I want to make sure the focus and API remain cohesive and consistent over time (i.e. I'm not a huge fan of what has happened to core draft-js since launch)

**Comment by benbriggs** [comment]
closing for housekeeping - i'm going to make an effort to be more proactive about keeping PRs from sitting around too long going forward.
