### ISSUE TITLE
Is there any way to avoid errors on server side?

### ISSUE THREAD

**Issue by kuatro** [HubSpot/draft-convert#41]
I'm trying to implement an isomorphic render, including Draft.js + draft-convert. Client-side works fine, but I'm facing a problem on server-side.

`/src/utils/parseHTML.js` contains a function `fallback()` which using `document`. Of course there is no `document` when you on server-side, so the question is – how to avoid that problem?

**Comment by benbriggs** [comment]
The arguments for using `convertToHTML` include a `DOMBuilder` argument that may be supplied to use instead of what's in `parseHTML` - a common replacement is using `jsdom` to parse an HTML string into a `BodyElement`.

As a side note your issue and some recent attempts to run tests in a node environment instead of a browser environment reminded me that there's another use of `document` [elsewhere](https://github.com/HubSpot/draft-convert/blob/master/src/convertFromHTML.js#L389-L396) when handling atomic blocks with entities inside - though this behavior can be avoided by using block metadata instead.

**Comment by kuatro** [comment]
@benbriggs Thank you. But, actually, still not clear for me. Is it possible to make kind of workaround to avoid server-side errors?

**Comment by benbriggs** [comment]
Yep, if you pass a `DOMBuilder` like this to convertFromHTML it should avoid using `document`:
```
const contentState = convertFromHTML(html, DOMBuilder);
```

where `DOMBuilder` is either a function wrapping `jsdom.env()` or just `jsdom.jsdom()` depending on how safe you feel about your incoming HTML.

**Comment by benbriggs** [comment]
Closing this as I believe using `jsdom` should fit the usecase - it's what the tests use when running in jest

**Comment by mwickett** [comment]
I'm trying to convert some HTML content as we migrate from an old platform to a new client app using draft-js, and I'm having difficulty understanding how to use this in a Node script. Specifically, I keep getting `document not defined`, even when passing in `jsdom`.
