### ISSUE TITLE
convertFromHTML/convertToHTML removes <a> tags and styles

### ISSUE THREAD

**Issue by palmerev** [HubSpot/draft-convert#65]
I'm using convertFromHTML and convertToHTML as documented in the README, but the resulting EditorState and HTML, respectively, seem to remove any applied inline styles and <a> tags. See screenshots.
The original HTML has a red paragraph:
<img width="1126" alt="screen shot 2017-04-25 at 8 48 20 pm" src="https://cloud.githubusercontent.com/assets/8763349/25417865/3748bc28-29fc-11e7-8b53-0fd649fa2f0c.png">

After running `const textState = EditorState.createWithContent(convertFromHTML(defaultText))` where `defaultText` is an HTML string, the EditorState in react-draft-wysiwyg doesn't have the red color applied anymore:
<img width="902" alt="screen shot 2017-04-25 at 8 42 32 pm" src="https://cloud.githubusercontent.com/assets/8763349/25417925/ac3670c0-29fc-11e7-9894-9022a37347d4.png">
So then when using convertToHTML, the result doesn't have the red color attribute either.

Similarly, if I create some colored text or a link in the editor directly, and use convertToHTML, the resulting HTML still doesn't have the text color, and the link tag is removed:
<img width="442" alt="screen shot 2017-04-25 at 9 07 50 pm" src="https://cloud.githubusercontent.com/assets/8763349/25418039/9061fd1e-29fd-11e7-95b4-93550df26425.png">
with `convertToHTML(snakeCaseEditors.registration_form_html.getCurrentContent())`
results in `<p>...We invite you to register to join our...</p>`

As far as I can tell, react-draft-wysiwyg isn't doing anything strange with EditorState. Am I missing some configuration? I'm not trying to do any custom formatting, just trying to maintain integrity through the conversion.

draft-convert 1.4.3
draft-js 0.10.0
react-draft-wysiwyg 1.9.4

**Comment by benbriggs** [comment]
`draft-convert` only includes definitions for styles that are built into Draft (bold, italic, underline, code), so you need to define behavior for any other styles you use via the options that you can provide to the conversion functions.

In your red text example the `color` style is on the `<p>` tag which is applied to the block. Something like text color is generally a modification that is made to a range of text rather than a block (as opposed to something like alignment). So I'd recommend first separating that style from the `<p>` tag and using a separate `<span>` or something to add the color. Assuming that your input uses that `<span>` instead, here's an example configuration of `convertFromHTML`. See the [advanced usage](https://github.com/HubSpot/draft-convert#convertfromhtml) parts of the documentation for additional examples:

```es6
const contentState = convertFromHTML({
  htmlToStyle: (nodeName, node, currentStyle) => {
    if (nodeName === 'span' && node.style.color === 'red') {
      return currentStyle.add('COLOR_RED'); // or whatever style key you use in your implementation of draft to define red text
    }
  }
})(html);
```

then when converting back to HTML:
```es6
const html = convertToHTML({
  styleToHTML: (style) => {
    if (style === 'COLOR_RED') {
      return <span style={{color: 'red'}} />;
    }
  }
})(contentState)
```
