### ISSUE TITLE
List item block should not be splitted in flat mode

### ISSUE THREAD

**Issue by lixiaoyan** [HubSpot/draft-convert#84]
html:

``` html
<ul><li>123<br />456</li></ul>
```

result in flat mode:

* 123
* 456

should be:

* 123  
  456

**Comment by benbriggs** [comment]
This is kind of the intent behind `flat` mode - to split every incoming visual new line into a separate block in the ContentState. I know this is technically an incorrect result, so that's why it's not the default behavior, and should only be used for when you care a lot about having flat blocks. Does the same issue persist in the default mode?

**Comment by lixiaoyan** [comment]
@benbriggs No, it only happens in flat mode.

**Comment by benbriggs** [comment]
OK, phew 😅  I think this is intended design of flat mode so I'm going to close this out and recommend using the default mode instead
